[commit_type_icons]
# Accessibility
access = "â™¿"

# Build configuration
build = "ğŸ“¦"

# Other changes
chore = "ğŸ§¹"

# Continuous integration configuration
ci = "ğŸ‘·"

# Configuration
config = "âš™ï¸ "

# Deprecation
deprecate = "âš ï¸"

# Documentation
docs = "ğŸ“š"

# New feature
feat = "âœ¨"

# Bug fix
fix = "ğŸ›"

# Initial Commit
init = "ğŸ‰"

# Language, Internationalization
lang = "ğŸŒ"

# Branch merge
merge = "ğŸ“¥"

# Metadata
metadata = "ğŸ“‡"

# Performance optimization
perf = "âš¡"

# Refactoring
refactor = "â™»ï¸ "

# Version releasing
release = "ğŸ"

# Removal
remove = "ğŸ—‘ï¸"

# Commit reversion
revert = "âª"

# Security fix
secfix = "ğŸ”’"

# Cosmetic
style = "ğŸ¨"

# version tag
tag = "ğŸ”–"

# Test addition or correction
test = "âœ…"

# Tool integration
tool = "ğŸ”§"

# Typo correction
typo = "âœï¸ "

# Work In Progress
wip = "ğŸš§"
